import uuid from "uuid/v4";
import { complaintsCreator } from "./functions/complaintsCreator";
import { anamnesisMorbiCreator } from "./functions/anamnesisMorbiCreator";
import { anamnesisVitaeCreator } from "./functions/anamnesisVitaeCreator";
import { statusPraesensCreator } from "./functions/statusPraesensCreator";
import { statusLocalisCreator } from "./functions/statusLocalisCreator";
import { diagnosisCreator } from "./functions/diagnosisCreator";
import { treatmentCreator } from "./functions/treatmentCreator";
import { operationNameCreator } from "./functions/operationNameCreator";
import { operationContentCreator } from "./functions/operationContentCreator";
import { lastTimeChecker } from "./functions/lastTimeChecker";
import { recommendationsCreator } from "./functions/recommendationsCreator";
import { colorIndexCounter } from "./functions/colorIndexCounter";
import { monoCounter } from "./functions/monoCounter";
import { diaryListCreator } from "./functions/diaryListCreator";
import { respiratoryRateCounter } from "./functions/respiratoryRateCounter";
import { heartRateCounter } from "./functions/heartRateCounter";
import { someDayCreator } from "./functions/someDayCreator";
import { lastDayCreator } from "./functions/lastDayCreator";
import { plannedChecker } from "./functions/plannedChecker";
import { patientEditor } from "./functions/patientEditor";
import {
  formulaMounter,
  finalFormulaMounter
} from "./functions/formulaMounter";
import { patientTemplate, formulaTemplate } from "./templates";

export const PATIENTS_ACTIONS = {
  ADD: "add",
  REMOVE: "remove",
  DISCHARGEADD: "dischargeadd",
  EXTRACTADD: "extractadd",
  OPERATIONADD: "operationadd",
  EDIT: "edit"
};

export const initialState = () => {
  const patientsFromStorage = localStorage.getItem("patients");
  const parsedPatients = JSON.parse(patientsFromStorage);
  return parsedPatients || [patientTemplate];
};

export const patientsReducer = (patients, action) => {
  // const {disease, startDay, startMonth /*and so on... as destructuring with removing word action*/} = action;
  switch (action.type) {
    case PATIENTS_ACTIONS.ADD:
      return [
        {
          _id: uuid(),
          disease: action.disease,
          reviewDate: `${action.startDay}.${action.startMonth}.${action.startYear}`,
          cardNumber: action.cardNumber,
          name: action.name,
          doctor: action.doctor,
          toothCasual: action.toothCasual,
          start1: action.start1,
          start2: action.start2,
          pregnancy: action.pregnancy,
          childbirth: action.childbirth,
          birthWeight: action.birthWeight,
          condition: action.condition,
          weight: action.weight,
          age: action.age,
          crownDestruction: action.crownDestruction,
          inflammationArea: action.inflammationArea,
          planned: plannedChecker(action.disease),
          drugs: [
            treatmentCreator(action.drugName1, action.age, action.weight),
            treatmentCreator(action.drugName2, action.age, action.weight),
            treatmentCreator(action.drugName3, action.age, action.weight),
            treatmentCreator(action.drugName4, action.age, action.weight),
            treatmentCreator(action.drugName5, action.age, action.weight),
            action.appointment,
            action.appointment2,
            action.appointment3
          ],
          drugName1: action.drugName1,
          drugName2: action.drugName2,
          drugName3: action.drugName3,
          drugName4: action.drugName4,
          drugName5: action.drugName5,
          appointment: action.appointment,
          appointment2: action.appointment2,
          appointment3: action.appointment3,
          protocolNumber: action.protocolNumber,
          operationDate: action.operationDate,
          operationTime: action.operationTime,
          pliers: action.pliers,
          elevator: action.elevator,
          duration: action.duration,
          surgeon: action.surgeon,
          assistant: action.assistant,
          anesthetist: action.anesthetist,
          woundArea: action.woundArea,
          woundSide: action.woundSide,
          injuryDate: action.injuryDate,
          injuryTime: action.injuryTime,
          injuryReason: action.injuryReason,
          woundType: action.woundType,
          woundLength: action.woundLength,
          woundWidth: action.woundWidth,
          woundDepth: action.woundDepth,
          woundForm: action.woundForm,
          woundLedges: action.woundLedges,
          woundBleeding: action.woundBleeding,
          woundAliens: action.woundAliens,
          sutureType: action.sutureType,
          sutureMaterial: action.sutureMaterial,
          sutureSize: action.sutureSize,
          startDay: action.startDay,
          startMonth: action.startMonth,
          startYear: action.startYear,
          retention1: action.retention1,
          retention2: action.retention2,
          retention3: action.retention3,
          retention4: action.retention4,
          overCompleteAmount: action.overCompleteAmount,
          overCompleteTooth1: action.overCompleteTooth1,
          overCompleteTooth2: action.overCompleteTooth2,
          overCompleteTooth3: action.overCompleteTooth3,
          overCompleteTooth4: action.overCompleteTooth4,
          cystDiameter: action.cystDiameter,
          operationDataSend: false,
          isTemporaryToothAbove: action.isTemporaryToothAbove,
          cystType: action.cystType,
          neoplasmType: action.neoplasmType,
          neoplasmArea: action.neoplasmArea,
          neoplasmSide: action.neoplasmSide,
          growthRate: action.growthRate,
          nepolasmSurface: action.neoplasmSurface,
          neoplasmMovability: action.neoplasmMovability,
          neoplasmPoignancy: action.neoplasmPoignancy,
          neoplasmConsistance: action.neoplasmConsistance,
          neoplasmDiameter: action.neoplasmDiameter,
          neoplasmColor: action.neoplasmColor,
          neoplasmBorders: action.neoplasmBorders,
          nepolasmAboveSurface: action.neoplasmAboveSurface,
          neoplasmSurfaceAlter: action.neoplasmSurfaceAlter,
          neoplasmForm: action.neoplasmForm,
          bilateralismLower: action.bilateralismLower,
          fractureLowerArea1: action.fractureLowerArea1,
          fractureLowerSide1: action.fractureLowerSide1,
          fractureLowerBias1: action.fractureLowerBias1,
          fractureLowerDirection1: action.fractureLowerDirection1,
          fractureLowerTooth1a: action.fractureLowerTooth1a,
          fractureLowerTooth1b: action.fractureLowerTooth1b,
          fractureLowerTeethInLine1: action.fractureLowerTeethInLine1,
          fractureLowerStep1: action.fractureLowerStep1,
          lowerJawSubmucous1: action.lowerJawSubmucous1,
          fractureLowerArea2: action.fractureLowerArea2,
          fractureLowerSide2: action.fractureLowerSide2,
          fractureLowerBias2: action.fractureLowerBias2,
          fractureLowerDirection2: action.fractureLowerDirection2,
          fractureLowerTooth2a: action.fractureLowerTooth2a,
          fractureLowerTooth2b: action.fractureLowerTooth2b,
          fractureLowerTeethInLine2: action.fractureLowerTeethInLine2,
          fractureLowerStep2: action.fractureLowerStep2,
          lowerJawSubmucous2: action.lowerJawSubmucous2,
          xRay: action.xRay,
          continuity: action.continuity,
          fractureOperationType: action.fractureOperationType,
          dlType: action.dlType,
          dlOperationType: action.dlOperationType,
          dlAlveolusDestroyed: action.dlAlveolusDestroyed,
          dlDirection: action.dlDirection,
          dlDistance: action.dlDistance,
          dlDeployed: action.dlDeployed,
          dlTooth1: action.dlTooth1,
          dlTooth2: action.dlTooth2,
          dlTooth3: action.dlTooth3,
          dlType2: action.dlTyp2,
          dlOperationType2: action.dlOperationType2,
          dlAlveolusDestroyed2: action.dlAlveolusDestroyed2,
          dlDirection2: action.dlDirection2,
          dlDistance2: action.dlDistance2,
          dlDeployed2: action.dlDeployed2,
          dlTooth4: action.dlTooth4,
          dlTooth5: action.dlTooth5,
          dlTooth6: action.dlTooth6,
          overCompleteForm: action.overCompleteForm,
          overCompleteForm2: action.overCompleteForm2,
          overCompleteLocation: action.overCompleteLocation,
          overCompleteLocation2: action.overCompleteLocation2,
          overCompleteXRay: action.overCompleteXRay,

          complaintsContent: complaintsCreator(
            action.disease,
            action.toothCasual,
            action.woundArea,
            action.woundSide,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.cystTooth,
            action.cystType,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmPoignancy,
            action.neoplasmArea,
            action.neoplasmSide,
            action.fractureLowerSide1,
            action.fractureLowerSide2,
            action.dlType,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlType2,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteLocation,
            action.overCompleteAmount
          ),
          anamnesisMorbiContent: anamnesisMorbiCreator(
            action.disease,
            action.toothCasual,
            action.start1,
            action.start2,
            action.injuryDate,
            action.injuryTime,
            action.injuryReason,
            action.abscessType,
            action.abscessReason,
            action.abscessSide,
            action.cystTooth,
            action.cystType,
            action.rootSealed,
            action.growthRate
          ),
          anamnesisVitaeContent: anamnesisVitaeCreator(
            action.pregnancy,
            action.childbirth,
            action.birthWeight
          ),
          statusPraesensContent: statusPraesensCreator(
            action.condition,
            action.age
          ),
          shortStatusContent: statusLocalisCreator(
            false,
            action.disease,
            action.toothCasual,
            action.inflammationArea,
            action.age,
            action.crownDestruction,
            action.woundSide,
            action.woundArea,
            action.woundType,
            action.woundLength,
            action.woundWidth,
            action.woundDepth,
            action.woundForm,
            action.woundLedges,
            action.woundBleeding,
            action.woundAliens,
            action.perioTeeth,
            action.changedList,
            action.woundSurface,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.abscessTooth,
            action.cystTooth,
            action.cystDiameter,
            action.isTemporaryToothAbove,
            action.cystType,
            action.rootSealed,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmArea,
            action.neoplasmSide,
            action.neoplasmForm,
            action.neoplasmBorders,
            action.neoplasmMovability,
            action.neoplasmPoignancy,
            action.neoplasmConsistance,
            action.neoplasmDiameter,
            action.neoplasmSurface,
            action.neoplasmColor,
            action.neoplasmAboveSurface,
            action.neoplasmSurfaceAlter,
            action.fractureLowerArea1,
            action.fractureLowerSide1,
            action.fractureLowerStep1,
            action.fractureLowerBias1,
            action.lowerJawSubmucous2,
            action.xRay,
            action.continuity,
            action.fractureLowerDirection1,
            action.condition,
            action.bilateralismLower,
            action.fractureLowerTooth1a,
            action.fractureLowerTooth1b,
            action.fractureLowerTeethInLine1,
            action.fractureLowerArea2,
            action.fractureLowerSide2,
            action.fractureLowerStep2,
            action.fractureLowerBias2,
            action.lowerJawSubmucous2,
            action.fractureLowerTooth2a,
            action.fractureLowerTooth2b,
            action.fractureLowerTeethInLine2,
            action.fractureLowerDirection2,
            action.dlAlveolusDestroyed,
            action.dlDirection,
            action.dlDistance,
            action.dlDeployed,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlType,
            action.dlAlveolusDestroyed2,
            action.dlDirection2,
            action.dlDistance2,
            action.dlDeployed2,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlType2,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.overCompleteLocation,
            action.overCompleteForm,
            action.overCompleteXRay,
            action.overCompleteAmount
          ),
          changedList: action.changedList,
          statusLocalisContent: statusLocalisCreator(
            true,
            action.disease,
            action.toothCasual,
            action.inflammationArea,
            action.age,
            action.crownDestruction,
            action.woundSide,
            action.woundArea,
            action.woundType,
            action.woundLength,
            action.woundWidth,
            action.woundDepth,
            action.woundForm,
            action.woundLedges,
            action.woundBleeding,
            action.woundAliens,
            action.perioTeeth,
            action.changedList,
            action.woundSurface,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.abscessTooth,
            action.cystTooth,
            action.cystDiameter,
            action.isTemporaryToothAbove,
            action.cystType,
            action.rootSealed,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmArea,
            action.neoplasmSide,
            action.neoplasmForm,
            action.neoplasmBorders,
            action.neoplasmMovability,
            action.neoplasmPoignancy,
            action.neoplasmConsistance,
            action.neoplasmDiameter,
            action.neoplasmSurface,
            action.neoplasmColor,
            action.neoplasmAboveSurface,
            action.neoplasmSurfaceAlter,
            action.fractureLowerArea1,
            action.fractureLowerSide1,
            action.fractureLowerStep1,
            action.fractureLowerBias1,
            action.lowerJawSubmucous1,
            action.xRay,
            action.continuity,
            action.fractureLowerDirection1,
            action.condition,
            action.bilateralismLower,
            action.fractureLowerTooth1a,
            action.fractureLowerTooth1b,
            action.fractureLowerTeethInLine1,
            action.fractureLowerArea2,
            action.fractureLowerSide2,
            action.fractureLowerStep2,
            action.fractureLowerBias2,
            action.lowerJawSubmucous2,
            action.fractureLowerTooth2a,
            action.fractureLowerTooth2b,
            action.fractureLowerTeethInLine2,
            action.fractureLowerDirection2,
            action.dlAlveolusDestroyed,
            action.dlDirection,
            action.dlDistance,
            action.dlDeployed,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlType,
            action.dlAlveolusDestroyed2,
            action.dlDirection2,
            action.dlDistance2,
            action.dlDeployed2,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlType2,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.overCompleteLocation,
            action.overCompleteForm,
            action.overCompleteXRay,
            action.overCompleteAmount
          ),
          diagnosis: diagnosisCreator(
            action.disease,
            action.toothCasual,
            action.woundType,
            action.woundArea,
            action.woundSide,
            action.perioTeeth,
            action.changedList,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.abscessReason,
            action.abscessTooth,
            action.cystTooth,
            action.cystType,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmType,
            action.neoplasmArea,
            action.neoplasmSide,
            action.fractureLowerArea1,
            action.fractureLowerSide1,
            action.fractureLowerBias1,
            action.fractureLowerTooth1a,
            action.fractureLowerTooth1b,
            action.fractureLowerTeethInLine1,
            action.bilateralismLower,
            action.fractureLowerArea2,
            action.fractureLowerSide2,
            action.fractureLowerBias2,
            action.fractureLowerTooth2a,
            action.fractureLowerTooth2b,
            action.fractureLowerTeethInLine2,
            action.dlType,
            action.dlType2,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.overCompleteAmount
          ),
          finalDiagnosis: diagnosisCreator(
            action.disease,
            action.toothCasual,
            action.woundType,
            action.woundArea,
            action.woundSide,
            action.perioTeeth,
            action.changedList,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.abscessReason,
            action.abscessTooth,
            action.cystTooth,
            action.cystType,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmType,
            action.neoplasmArea,
            action.neoplasmSide,
            action.fractureLowerArea1,
            action.fractureLowerSide1,
            action.fractureLowerBias1,
            action.fractureLowerTooth1a,
            action.fractureLowerTooth1b,
            action.fractureLowerTeethInLine1,
            action.bilateralismLower,
            action.fractureLowerArea2,
            action.fractureLowerSide2,
            action.fractureLowerBias2,
            action.fractureLowerTooth2a,
            action.fractureLowerTooth2b,
            action.fractureLowerTeethInLine2,
            action.dlType,
            action.dlType2,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.overCompleteAmount
          ),
          diagnosisCap:
            diagnosisCreator(
              action.disease,
              action.toothCasual,
              action.woundType,
              action.woundArea,
              action.woundSide,
              action.perioTeeth,
              action.changedList,
              action.abscessType,
              action.abscessArea,
              action.abscessSide,
              action.abscessReason,
              action.abscessTooth,
              action.cystTooth,
              action.cystType,
              action.retention1,
              action.retention2,
              action.retention3,
              action.retention4,
              action.neoplasmType,
              action.neoplasmArea,
              action.neoplasmSide,
              action.fractureLowerArea1,
              action.fractureLowerSide1,
              action.fractureLowerBias1,
              action.fractureLowerTooth1a,
              action.fractureLowerTooth1b,
              action.fractureLowerTeethInLine1,
              action.bilateralismLower,
              action.fractureLowerArea2,
              action.fractureLowerSide2,
              action.fractureLowerBias2,
              action.fractureLowerTooth2a,
              action.fractureLowerTooth2b,
              action.fractureLowerTeethInLine2,
              action.dlType,
              action.dlType2,
              action.dlTooth1,
              action.dlTooth2,
              action.dlTooth3,
              action.dlTooth4,
              action.dlTooth5,
              action.dlTooth6,
              action.overCompleteTooth1,
              action.overCompleteTooth2,
              action.overCompleteTooth3,
              action.overCompleteTooth4,
              action.overCompleteAmount
            )[0].toUpperCase() +
            diagnosisCreator(
              action.disease,
              action.toothCasual,
              action.woundType,
              action.woundArea,
              action.woundSide,
              action.perioTeeth,
              action.changedList,
              action.abscessType,
              action.abscessArea,
              action.abscessSide,
              action.abscessReason,
              action.abscessTooth,
              action.cystTooth,
              action.cystType,
              action.retention1,
              action.retention2,
              action.retention3,
              action.retention4,
              action.neoplasmType,
              action.neoplasmArea,
              action.neoplasmSide,
              action.fractureLowerArea1,
              action.fractureLowerSide1,
              action.fractureLowerBias1,
              action.fractureLowerTooth1a,
              action.fractureLowerTooth1b,
              action.fractureLowerTeethInLine1,
              action.bilateralismLower,
              action.fractureLowerArea2,
              action.fractureLowerSide2,
              action.fractureLowerBias2,
              action.fractureLowerTooth2a,
              action.fractureLowerTooth2b,
              action.fractureLowerTeethInLine2,
              action.dlType,
              action.dlType2,
              action.dlTooth1,
              action.dlTooth2,
              action.dlTooth3,
              action.dlTooth4,
              action.dlTooth5,
              action.dlTooth6,
              action.overCompleteTooth1,
              action.overCompleteTooth2,
              action.overCompleteTooth3,
              action.overCompleteTooth4,
              action.overCompleteAmount
            ).slice(1),
          operationName: operationNameCreator(
            action.disease,
            action.toothCasual,
            action.woundArea,
            action.woundSide,
            action.perioTeeth,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.cystTooth,
            action.cystType,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmArea,
            action.neoplasmSide,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlOperationType,
            action.dlOperationType2,
            action.overCompleteAmount
          ),
          operationNameCap:
            operationNameCreator(
              action.disease,
              action.toothCasual,
              action.woundArea,
              action.woundSide,
              action.perioTeeth,
              action.abscessType,
              action.abscessArea,
              action.abscessSide,
              action.cystTooth,
              action.cystType,
              action.retention1,
              action.retention2,
              action.retention3,
              action.retention4,
              action.neoplasmArea,
              action.neoplasmSide,
              action.dlTooth1,
              action.dlTooth2,
              action.dlTooth3,
              action.dlTooth4,
              action.dlTooth5,
              action.dlTooth6,
              action.dlOperationType,
              action.dlOperationType2,
              action.overCompleteAmount
            )[0].toUpperCase() +
            operationNameCreator(
              action.disease,
              action.toothCasual,
              action.woundArea,
              action.woundSide,
              action.perioTeeth,
              action.abscessType,
              action.abscessArea,
              action.abscessSide,
              action.cystTooth,
              action.cystType,
              action.retention1,
              action.retention2,
              action.retention3,
              action.retention4,
              action.neoplasmArea,
              action.neoplasmSide,
              action.dlTooth1,
              action.dlTooth2,
              action.dlTooth3,
              action.dlTooth4,
              action.dlTooth5,
              action.dlTooth6,
              action.dlOperationType,
              action.dlOperationType2,
              action.overCompleteAmount
            ).slice(1),
          operationContent: operationContentCreator(
            action.disease,
            action.toothCasual,
            action.inflammationArea,
            action.pliers,
            action.elevator,
            action.sutureType,
            action.sutureMaterial,
            action.sutureSize,
            action.perioTeeth,
            action.changedList,
            "",
            action.anestesiaType,
            action.woundSurface,
            action.abscessType,
            action.abscessArea,
            action.abscessSide,
            action.abscessReason,
            action.abscessTooth,
            action.cystTooth,
            action.cystType,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmArea,
            action.fractureOperationType,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlOperationType,
            action.dlOperationType2,
            action.overCompleteTooth1,
            action.overCompleteTooth2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.overCompleteAmount
          ),
          perioTeeth: action.perioTeeth,
          heartRate: heartRateCounter(action.age),
          respiratoryRate: respiratoryRateCounter(action.age),
          lastTime: lastTimeChecker(action.operationTime),
          someDayContent: someDayCreator(
            action.disease,
            action.toothCasual,
            action.abscessArea,
            action.abscessSide,
            action.abscessType,
            action.cystTooth,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.neoplasmSurface,
            action.fractureLowerArea1,
            action.fractureLowerSide1,
            action.fractureLowerArea2,
            action.fractureLowerSide2,
            action.bilateralismLower,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlOperationType,
            action.dlOperationType2,
            action.overCompleteTooth3,
            action.overCompleteTooth4
          ),
          lastDayContent: lastDayCreator(
            action.disease,
            action.retention1,
            action.retention2,
            action.retention3,
            action.retention4,
            action.dlTooth1,
            action.dlTooth2,
            action.dlTooth3,
            action.dlTooth4,
            action.dlTooth5,
            action.dlTooth6,
            action.dlOperationType,
            action.dlOperationType2,
            action.overCompleteTooth3,
            action.overCompleteTooth4,
            action.abscessArea
          ),
          diaryList: [
            {
              date: `${action.startDay}.${action.startMonth}.${action.startYear}`,
              workDay: true
            }
          ],
          epicrisisDataSend: false,
          extractDataSend: false,
          anestesiaType: action.anestesiaType,
          abscessType: action.abscessType,
          abscessArea: action.abscessArea,
          abscessSide: action.abscessSide,
          abscessReason: action.abscessReason,
          abscessTooth: action.abscessTooth,
          cystTooth: action.cystTooth,
          rootSealed: action.rootSealed,
          toothFormula: formulaMounter(
            formulaTemplate,
            action.age,
            action.changedList
          ),
          toothFormulaPost: formulaMounter(
            formulaTemplate,
            action.age,
            action.changedList
          )
        },
        ...patients
      ];
    case PATIENTS_ACTIONS.REMOVE:
      return patients.filter((patient) => action._id !== patient._id);
    case PATIENTS_ACTIONS.DISCHARGEADD:
      return patients.map((patient) =>
        patient._id === action._id
          ? {
              ...patient,
              recommendations: recommendationsCreator(
                patient.disease,
                patient.age
              ),
              dischargeDate: `${action.lastDay}.${action.lastMonth}.${action.lastYear}`,
              diaryList: diaryListCreator(
                patient.startDay,
                patient.startMonth,
                patient.startYear,
                action.lastDay,
                action.lastMonth,
                action.lastYear
              ),
              hb: action.hb,
              er: action.er,
              colorIndex: colorIndexCounter(action.hb, action.er),
              leu: action.leu,
              pal: action.pal,
              segm: action.segm,
              eoz: action.eoz,
              limf: action.limf,
              mono: monoCounter(
                action.pal,
                action.segm,
                action.eoz,
                action.limf
              ),
              rse: action.rse,
              bloodTest: [
                action.hb,
                action.er,
                colorIndexCounter(action.hb, action.er),
                action.leu,
                action.pal,
                action.segm,
                action.eoz,
                action.limf,
                monoCounter(action.pal, action.segm, action.eoz, action.limf),
                action.rse
              ],
              uColor: action.uColor,
              uOpacity: action.uOpacity,
              uWeight: action.uWeight,
              uPh: action.uPh,
              uProtein: action.uProtein,
              uLeu: action.uLeu,
              uEp1: action.uEp1,
              uEp2: action.uEp2,
              urineTest: [
                action.uColor,
                action.uOpacity,
                action.uWeight,
                action.uPh,
                action.uProtein,
                action.uLeu,
                action.uEp1,
                action.uEp2,
                action.uOther
              ],
              glucose: action.glucose,
              enterobioz: action.enterobioz,
              dung: action.dung,
              bloodGroup: action.bloodGroup,
              rezusFactor: action.rezusFactor,
              wasViolation: action.wasViolation,
              epicrisisDataSend: true,
              finalDiagnosis: action.finalDiagnosis,
              anestesiaTypeModified: `${patient.anestesiaType[0].toLowerCase()}${patient.anestesiaType.slice(
                1,
                patient.anestesiaType.length - 1
              )}им`
            }
          : patient
      );
    case PATIENTS_ACTIONS.EXTRACTADD:
      return patients.map((patient) =>
        patient._id === action._id
          ? {
              ...patient,
              birthDate: `${action.birthDay}.${action.birthMonth}.${action.birthYear} р.н.`,
              fullAdress: `${action.town}${action.adress}${action.district}${action.village}${action.otherRegion}.`,
              extractDataSend: true,
              anestesiaTypeModified: `${patient.anestesiaType[0].toLowerCase()}${patient.anestesiaType.slice(
                1,
                patient.anestesiaType.length - 1
              )}им`
            }
          : patient
      );
    case PATIENTS_ACTIONS.OPERATIONADD:
      return patients.map((patient) =>
        patient._id === action._id
          ? {
              ...patient,
              protocolNumber: action.protocolNumber,
              anestesiaType: action.anestesiaType,
              operationDate: action.operationDate,
              operationTime: action.operationTime,
              toothFormulaPost: finalFormulaMounter(
                patient.toothFormula,
                action.changedList
              ),
              operationContent: operationContentCreator(
                patient.disease,
                patient.toothCasual,
                patient.inflammationArea,
                action.pliers,
                action.elevator,
                action.sutureType,
                action.sutureMaterial,
                action.sutureSize,
                patient.perioTeeth,
                action.changedList,
                action.restMaterial,
                action.anestesiaType,
                patient.woundSurface,
                patient.abscessType,
                patient.abscessArea,
                patient.abscessSide,
                patient.abscessReason,
                patient.abscessTooth,
                patient.cystTooth,
                patient.cystType,
                patient.retention1,
                patient.retention2,
                patient.retention3,
                patient.retention4,
                patient.neoplasmArea,
                patient.fractureOperationType,
                patient.dlTooth1,
                patient.dlTooth2,
                patient.dlTooth3,
                patient.dlTooth4,
                patient.dlTooth5,
                patient.dlTooth6,
                patient.dlOperationType,
                patient.dlOperationType2,
                patient.overCompleteTooth1,
                patient.overCompleteTooth2,
                patient.overCompleteTooth3,
                patient.overCompleteTooth4,
                patient.overCompleteAmount
              ),
              duration: action.duration,
              surgeon: action.surgeon,
              assistant: action.assistant,
              anesthetist: action.anesthetist,
              lastTime: lastTimeChecker(action.operationTime),
              operationDataSend: true,
              finalDiagnosis: diagnosisCreator(
                patient.disease,
                patient.toothCasual,
                patient.woundType,
                patient.woundArea,
                patient.woundSide,
                patient.perioTeeth,
                action.changedList,
                patient.abscessType,
                patient.abscessArea,
                patient.abscessSide,
                patient.abscessReason,
                patient.abscessTooth,
                patient.cystTooth,
                patient.cystType,
                patient.retention1,
                patient.retention2,
                patient.retention3,
                patient.retention4,
                patient.neoplasmType,
                patient.neoplasmArea,
                patient.neoplasmSide,
                patient.fractureLowerArea1,
                patient.fractureLowerSide1,
                patient.fractureLowerBias1,
                patient.fractureLowerTooth1a,
                patient.fractureLowerTooth1b,
                patient.fractureLowerTeethInLine1,
                patient.bilateralismLower,
                patient.fractureLowerArea2,
                patient.fractureLowerSide2,
                patient.fractureLowerBias2,
                patient.fractureLowerTooth2a,
                patient.fractureLowerTooth2b,
                patient.fractureLowerTeethInLine2,
                patient.dlType,
                patient.dlType2,
                patient.dlTooth1,
                patient.dlTooth2,
                patient.dlTooth3,
                patient.dlTooth4,
                patient.dlTooth5,
                patient.dlTooth6,
                patient.overCompleteTooth1,
                patient.overCompleteTooth2,
                patient.overCompleteTooth3,
                patient.overCompleteTooth4,
                patient.overCompleteAmount
              )
            }
          : patient
      );
    case PATIENTS_ACTIONS.EDIT:
      return patients.map((patient) =>
        patient._id === action._id
          ? patientEditor(action.editType, patient, action.editedValue)
          : patient
      );
    // case PATIENTS_ACTIONS.CARDNUMBERSORT:
    //   return patients.sort(function (a, b) {
    //     return Number(b.cardNumber) - Number(a.cardNumber);
    //   });
    // case PATIENTS_ACTIONS.NAMESORT:
    //   return patients.sort(function (a, b) {
    //     return a.name.localeCompare(b.name);
    //   });
    // case PATIENTS_ACTIONS.DISEASESORT:
    //   return patients.sort(function (a, b) {
    //     return a.disease.localeCompare(b.disease);
    //   });
    // case PATIENTS_ACTIONS.REQUESTSORT:
    //   let regExp = new RegExp(action.request);
    //   return patients.sort(function (a, b) {
    //     if (!regExp.test(a.name)) {
    //       return 1;
    //     }
    //     if (regExp.test(a.name)) {
    //       return -1;
    //     }
    //     return 0;
    //   });
    default:
      throw new Error();
  }
};
